### ISSUE TITLE
system.ArgumentException

### ISSUE THREAD

**Issue by jaleel2007** [yellowfeather/DbfDataReader#1]
Hi Chris Richards;
i got this error when try to iterate over the rows. I just copy the code list in : "and to iterate over the rows:" section.
**system.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()**

and how can i convert this line to a datatable ? "var dbfTable = new DbfTable(dbfPath)"

**Comment by jaleel2007** [comment]
i ues following dbf file:

[MS__KHDM.zip](https://github.com/yellowfeather/DbfDataReader/files/1167134/MS__KHDM.zip)

**Comment by chrisrichards** [comment]
Thanks, I'll take a look

**Comment by pocki** [comment]
I had the same issue. My fix was to set the encoding like this: 
var dbfTable = new DbfTable(dbfPath, Encoding.GetEncoding(1252))
