### ISSUE TITLE
Please consider restoring support for .NET Framework by supporting .NET Standard 2.0

### ISSUE THREAD

**Issue by jnm2** [yellowfeather/DbfDataReader#105]
We're using this in a .NET Framework project which isn't ready to move to .NET Core because of other third party libraries.

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting suggests targeting .NET Standard 2.0. For us, targeting `net48;netstandard2.1` would also work fine.

You can still use `ReadOnlySpan<T>` by adding a reference to https://www.nuget.org/packages/System.Memory without dropping support for .NET Framework apps.

**Comment by chrisrichards** [comment]
Just released v0.7.0 with net48 support. Not quite as simple as first thought due to BitConverter not accepting Span arguments.

**Comment by jnm2** [comment]
Thank you!
