### ISSUE TITLE
Currency values are not read consistently 

### ISSUE THREAD

**Issue by burdickryan** [yellowfeather/DbfDataReader#11]
[sect_iia.zip](https://github.com/yellowfeather/DbfDataReader/files/1553465/sect_iia.zip)
In the example attached, Field45, which has a value of 743280 in the DBF table, is not read. Field7, which has a value of 71475, is read as expected.

Here is the extension method I use to read the data:

```
        public static T GetValue<T>(this DbfDataReader.DbfDataReader reader, string columnName)
        {
            var ordinal = reader.GetOrdinal(columnName);

            if (reader.IsDBNull(ordinal)) return default(T);

            return (T)Convert.ChangeType(reader.GetValue(ordinal), typeof(T));
        }

```
The reader returns DBNull for Field45.

Note that I get the same result when I use "straight" DbfDataReader methods such as GetDecimal, GetFloat, etc. 

I believe the problem might have something to do with the null binary check ("\0") in line 18 of DbfValueCurrency.cs, but I don't know enough about DBF to say for certain. 

When I skip that check for this particular field and allow the remaining code to execute I get the result I expect (743280). The "remaining code" refers to lines 24 and 25 in DbfValueCurrency.cs:

```
                var value = BitConverter.ToUInt64(bytes, 0);
                Value = value / 10000.0f;

```

**Comment by chrisrichards** [comment]
Fixed by #15
