### ISSUE TITLE
DbfDataReader Not Reading All Rows If Deleted Rows Exist

### ISSUE THREAD

**Issue by mhmoudalaskalany** [yellowfeather/DbfDataReader#146]
**Bug  Description**
DbfDataReader is Skipping Rows After Deleted Row if i set  SkipDeletedRecords = true

1. Read Dbf file that contains deleted record at index number (ex 100 from 500)
2. try to bulk copy the dbf file to sql server
3. copied rows will be rows before deleted record only which are 99 rows only

**Expected behavior**
it should read all rows and skip deleted rows

**Screenshots**

![Capture](https://user-images.githubusercontent.com/45127300/139940889-438d5778-1d3d-4fb7-86af-3ab2648a8c33.PNG)

**Desktop:**
 - OS: [e.g. windows 10]
 - Browser [e.g. chrome]
 - Version [e.g. 80]

**Comment by chrisrichards** [comment]
Have you got a test file for this? There's a test (which passes) for deleted records here https://github.com/yellowfeather/DbfDataReader/blob/d82c44949b2d9cca5795ab9fbdc29f8ce733cce1/test/DbfDataReader.Tests/DbfDataReaderTests.cs#L91

**Comment by mhmoudalaskalany** [comment]
@chrisrichards Thanks for the response , apology for late reply
no i did not , anyway we can close this issue we finished the project in our side and we did not use this functionality
