### ISSUE TITLE
FoxPro DBF with FPT memos failing to complete load

### ISSUE THREAD

**Issue by JenniferBlau-Mattang** [yellowfeather/DbfDataReader#147]
**Describe the bug**
Object reference not set to an instance of an object error

**To Reproduce**
Run the attached minimum solution with the included dbf/fpt files. 

**Expected behavior**
DBF to be read to the end with the memo files included

**Screenshots**
![image](https://user-images.githubusercontent.com/51751693/140362515-ca26fb91-7870-4093-b7b4-334a9c1d2074.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I also got a copy of your repo and found and locally fixed the issue here.
![image](https://user-images.githubusercontent.com/51751693/140363640-9003de8d-148b-421c-90d7-f684b05e970d.png)
 
It looks like someone has already submitted a pull request that would fix this issue. 
https://github.com/yellowfeather/DbfDataReader/pull/143

Minimum viable test application with test dbfs
[DbfReaderTest.zip](https://github.com/yellowfeather/DbfDataReader/files/7476116/DbfReaderTest.zip)

**Comment by xyrus02** [comment]
It is fixed with #186
