### ISSUE TITLE
Skip deleted and empty rows

### ISSUE THREAD

**Issue by W357** [yellowfeather/DbfDataReader#18]
Hey. Can you add an option to skip deleted or empty rows?

That would be great, Thanks =)

**Comment by chrisrichards** [comment]
Will do, although will be at least a couple of weeks as I’m on holiday.

**Comment by W357** [comment]
Cool thanks. Have a good time!

**Comment by chrisrichards** [comment]
Skip deleted rows is added in e96fbdf2c7585211ee8fa90ae45a0bf34fcf6d3d and will be in the next release.

Regarding empty rows, I think this would be application specific and best done outside of this library.
