### ISSUE TITLE
Date parsing issue

### ISSUE THREAD

**Issue by Shavrar** [yellowfeather/DbfDataReader#203]
Hello, I observe that some dates are not being read by reader, while older dates are fine. It's probably the same problem as in PR
Fixed DbfValueDateTime null values checking #159.

You can easily reproduce it with attached dbf file. Last 3 rows won't have any dates but in fox pro I can see those dates.

My code for reading:
```
private DataTable Read(string path, string tableName)
{
    var options = new DbfDataReader.DbfDataReaderOptions
    {
        //SkipDeletedRecords = true                 
        // Encoding = EncodingProvider.GetEncoding(1252);
    };

    using var dbfDataReader = new DbfDataReader.DbfDataReader($"{path}\\{tableName}.db", options);
    var columns = dbfDataReader.GetColumnSchema();
    var datatable = new DataTable();
    foreach (var column in columns)
    {
        datatable.Columns.Add(column.ColumnName, column.DataType);
    }
    datatable.Columns.Add("Deleted", typeof(int));
    while (dbfDataReader.Read())
    {
        var values = new object[datatable.Columns.Count];
        for (var i = 0; i < columns.Count; i++)
        {
            values[i] = dbfDataReader.GetValue(i);
        }
        values[columns.Count] = dbfDataReader.DbfRecord.IsDeleted ? 1 : 0;
        datatable.LoadDataRow(values, true);
    }
    return datatable;
}
```

[_PRM.zip](https://github.com/yellowfeather/DbfDataReader/files/12260863/_PRM.zip)

UPD:
![image](https://github.com/yellowfeather/DbfDataReader/assets/17605707/74cf9b61-e0aa-4e59-9cee-cd19fac0113b)

Debuged mentioned date parsing, as you can see it's not empty date but first byte is 0. So it's exatcly the same issue in #159

**Comment by Shavrar** [comment]
@chrisrichards Can you please check this issue or at least tell if it will be fixed at some point or not?

**Comment by chrisrichards** [comment]
On holiday at the moment, but will look at it when I’m back in 2-3 weeksOn 7 Aug 2023, at 16:47, Turlei Roman ***@***.***> wrote:﻿
@chrisrichards Can you please check this issue or at least tell if it will be fixed at some point or not?

**Comment by maninderjitSingh** [comment]
Having the same issue, below is what's working for me

`
public override void Read(ReadOnlySpan<byte> bytes)
        {
            var datePart = BitConverter.ToInt32(bytes);
            var timePart = BitConverter.ToInt32(bytes[4..]);

            // You could add additional validity checks here, based on your specific data and needs
            if (datePart == 0 && timePart == 0)
            {
                Value = null;
            }
            else
            {
                Value = new DateTime(1, 1, 1).AddDays(datePart).Subtract(TimeSpan.FromDays(1721426))
                    .AddMilliseconds(timePart);
            }
        }
`

**Comment by maninderjitSingh** [comment]
Was having the same issue so far trying the below, seems to be working for our requirements

```
public override void Read(ReadOnlySpan<byte> bytes)
        {
            var datePart = BitConverter.ToInt32(bytes);
            var timePart = BitConverter.ToInt32(bytes[4..]);

            // You could add additional validity checks here, based on your specific data and needs
            if (datePart == 0 && timePart == 0)
            {
                Value = null;
            }
            else
            {
                Value = new DateTime(1, 1, 1).AddDays(datePart).Subtract(TimeSpan.FromDays(1721426))
                    .AddMilliseconds(timePart);
            }
        }


```

**Comment by Shavrar** [comment]
@chrisrichards Hello, hope you had nice vacation. Have you had time to check issue and pr?
