### ISSUE TITLE
fpt for foxpro is not read well

### ISSUE THREAD

**Issue by Hasanajouz** [yellowfeather/DbfDataReader#4]
for my visual foxpro files the memo field was giving error after debugging i found where the problem is.
it was in converting byte[] to int: so i fixed those two methods with this: in this file "DbfMemoFoxPro.cs"
private int CalculateBlockSize()
        {
            _binaryReader.BaseStream.Seek(0, SeekOrigin.Begin);
            byte[] b = _binaryReader.ReadBytes(4);
            Array.Reverse(b);
            int x=BitConverter.ToInt32(b,0); // next block
            b = _binaryReader.ReadBytes(2);
            Array.Reverse(b);
            int xx= BitConverter.ToInt16(b, 0); // unused
            b = _binaryReader.ReadBytes(2);
            Array.Reverse(b);
            int xxx= BitConverter.ToInt16(b, 0);
            return xxx;
        }

        public override string BuildMemo(long startBlock)
        {
            var offset = Offset(startBlock);
            _binaryReader.BaseStream.Seek(offset, SeekOrigin.Begin);

            byte[] b = _binaryReader.ReadBytes(4);
            Array.Reverse(b);
            var blockType = BitConverter.ToInt32(b, 0);
            b = _binaryReader.ReadBytes(4);
            Array.Reverse(b);
            var memoLength = BitConverter.ToInt32(b, 0);

            if ((blockType != 1) || (memoLength == 0))
            {
                return string.Empty;
            }

            var memo = new string(_binaryReader.ReadChars(memoLength));
            memo = memo.Replace("\0","").Replace("\u0001","").Replace("\b","").TrimEnd('\0').Trim();
            return memo;
        }

**Comment by chrisrichards** [comment]
Thanks for this, however I've tried changing to the code above and it breaks the unit test for the dbase_30 file. What was used to generate the file you were having problems with? Are you able to provide a test file?

**Comment by Hasanajouz** [comment]
it is visual fox pro:
i just have to reverse the byte[] to be able to read it

**Comment by chrisrichards** [comment]
Are you able to supply a DBF and FPT file I could use to test?
