### ISSUE TITLE
Could not detect any platforms from '.NETStandard1.6.1' in DbfDataReader 0.5.2

### ISSUE THREAD

**Issue by HightowerCZ** [yellowfeather/DbfDataReader#48]
Hi after installing DbfDataReader from console, there is an error:
Could not detect any platforms from '.NETStandard1.6.1' in DbfDataReader 0.5.2, please tell the package authors.

Our project is a console application .Net Core 3.1.

Jakub

**Comment by chrisrichards** [comment]
Can you share an example project? There is a console app [dbf](https://github.com/yellowfeather/dbf) that is currently netcoreapp2.0 but I've just updated it locally to netcoreapp3.1 and it builds fine.

**Comment by Swoorup** [comment]
I am getting the same error as well. 
```
Could not detect any platforms from 'netstandard1.6.1' in '/home/sjoshi/.nuget/packages/dbfdatareader/0.5.4/lib/netstandard1.6.1/DbfDataReader.dll', please tell the package authors
```

Fairly certain as `netstandard1.6.1` is not a valid platform. I believe changing this line in https://github.com/yellowfeather/DbfDataReader/blob/master/src/DbfDataReader/DbfDataReader.csproj#L8
to 
`<TargetFrameworks>net452;netstandard1.6</TargetFrameworks>` will fix the issue

**Comment by chrisrichards** [comment]
Thanks, I've bumped the target framework to netstandard2.0
