### ISSUE TITLE
Column names are not handled properly

### ISSUE THREAD

**Issue by maciejpankanin** [yellowfeather/DbfDataReader#59]
I encountered problem using DbfDataReader. In DBFs I want to read some columns names do not end with **'\0'** sign which means I cannot use **GetOrdinal** method properly.

For example there is a column in dbf file like this: **"STREET\0\0\0\01"**. I looked into code, column names are handled in this way:
`Name = rawName.TrimEnd((char) 0);` which will not work for my example cause name does not end with '\0'.

My proposition is to use split instead of trim like this:
`Name = rawName.Split((char) 0)[0];`

**Comment by lqdchrm** [comment]
Some dbf-writer implementations don't fill the column names with zeros (probably come C-code, where strings are terminated with a single \0, and the space behind stays unchanged and might contain garbage). Your proposed change

`Name = rawName.Split((char) 0)[0];`

should actually work.

If I find time I will try to submit a PR.

**Comment by GerHobbelt** [comment]
Example of this issue in a legacy production database table:

![image](https://user-images.githubusercontent.com/402462/96611807-56f73700-12fd-11eb-8e81-ec3419f0873b.png)

Observe the cruft following each `<0x00>`: this application has been updated (changed) a few times in the last 20-odd years and was probably written in Clipper. Anyway, a single field name may contain more than one NUL byte, e.g. the field 'UUR' in the screenshot above, which clearly has been changed (at least) twice in its lifetime.

Hence for tiny bit of performance improvement this code change is suggested:

```
var nullIdx = rawName.IndexOf((char)0);
if (nullIdx >= 0)
{
  rawName = rawName.Substring(0, nullIdx);   // trim off everything past & including the first NUL byte
}
Name = rawName;
```
