### ISSUE TITLE
Integer Precisions not being interpreted create a value overflow 

### ISSUE THREAD

**Issue by makingglitches** [yellowfeather/DbfDataReader#98]
Luckily I updated the code :)
I believe we had a discussion about this the last time the world ended for no valid reason.

[src.zip](https://github.com/yellowfeather/DbfDataReader/files/5908362/src.zip)

Remember. Nukes go 3 places.
One is North Korea.
One is Colorado
and the other is a shit town named Enola and Wyoming just about makes 4.

**Comment by makingglitches** [comment]
I am wondering if he has not retired.

**Comment by chrisrichards** [comment]
Ha! Sadly not retired, just busy with other things.

Could you create a pull request for these changes?

**Comment by makingglitches** [comment]
> Ha! Sadly not retired, just busy with other things.
> 
> 
> 
> Could you create a pull request for these changes?

Sadly I'm not sure how to do that but no time like the present to learn I suppose 

The changes are included in the source zip I added but I'll have a look see

**Comment by makingglitches** [comment]
Oh ok I'll see if the modded file is in my repo
It should be

**Comment by makingglitches** [comment]
@chrisrichards do you have some unit tests for this ? Imma have to either just redo the code or do some merging because it looks like you made some updates that could cause conflicts in the files I fixed like half a year ago lol

**Comment by makingglitches** [comment]
@chrisrichards looks also like you updated to dotnet core v5 ? Am I right ?

**Comment by chrisrichards** [comment]
Yes, it is now net5.0 and netstandard2.1.

There are unit tests in the project already, but nothing specifically for integer precisions. If you have or can create a dbf file that can be used in a test that would be great!

**Comment by makingglitches** [comment]
@chrisrichards uh are you sure your code still works ?

All the dbf files I see contain string representations of the value which has to be converted to a string from the byte array to the value type.

The new code is skipping that and trying to draw a value from a byte array using bitconverter.todouble for example.

**Comment by makingglitches** [comment]
@chrisrichards if that works or ms made it smart enough to recognize the difference between a packed binary array and a string that needs parsed then their docs are off

**Comment by chrisrichards** [comment]
See DBF spec here http://dbase.com/Knowledgebase/INT/db7_file_fmt.htm

Numbers (N) - Number stored as a string, right justified, and padded with blanks to the width of the field. 
Float (F) - Number stored as a string, right justified, and padded with blanks to the width of the field. 
Long (l) - 4 bytes. Leftmost bit used to indicate sign, 0 negative.
Double (O) - 8 bytes - no conversions, stored as a double.

i.e. you can't use DbfValueLong for numbers with a length > 10 as they are stored differently

If you can provide a test DBF file that would help.

**Comment by makingglitches** [comment]
Sure but you don't seem to be getting what I'm saying.

https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter.touint64?view=net-5.0

BitConverter is taking an endian binary value and converting it to variable type.
Its not a TryParse or Parse.

Thats what the dbfDouble and DbfLong are behaving like.

**Comment by makingglitches** [comment]
[tl_2019_01_place.zip](https://github.com/yellowfeather/DbfDataReader/files/6727875/tl_2019_01_place.zip)

Is the original guy dead or something ? Because we keep doing this same crazy shit for no reason.

**Comment by makingglitches** [comment]
The failure in the original code was occurring because  it was always defaulting to Int32 column types if no decimal points were encountered which was cause issues when a parse was called, which was trying to parse a number bigger than it could fit in the value type, so I found the largest number that could be represented by a string, which happens to start with a 1,  and subtracted one digit of length as the cutoff point, so less than a 10 digit length and the column is int32, greater than, and its int64

**Comment by makingglitches** [comment]
Well so i partly fixed it except now I'm wondering why the numbers were correct i pulled from the damn file.

**Comment by makingglitches** [comment]
http://web.archive.org/web/20150323061445/http://ulisse.elettra.trieste.it/services/doc/dbase/DBFstruct.htm#T2.4

Thats what this project was reading. And its a format that is very very widely used to accompany ESRI shapefiles.

**Comment by chrisrichards** [comment]
The `tl_2019_01_place` file works fine, see https://github.com/yellowfeather/DbfDataReader/blob/d5b1141675b2973be05fd5e1419c45ff530c14a2/test/DbfDataReader.Tests/EsriShapefileTests.cs#L7

Can you provide a file that shows this issue?

**Comment by makingglitches** [comment]
https://dotnetfiddle.net/CBzHzs
Dude.

**Comment by makingglitches** [comment]
Hey what did I say when I said this was a waking nightmare

**Comment by chrisrichards** [comment]
This is now fixed, but please read the [conduct of conduct](https://github.com/yellowfeather/DbfDataReader/blob/e04e5a3b062f0b2f7ba3364d967177ed747c8286/CODE_OF_CONDUCT.md) before making any more contributions.
